version: '3.4'
services:
  mysql:
    image: "mysql:8.0"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 13306:3306
    volumes:
      - ./script/mysql/:/docker-entrypoint-initdb.d