apiVersion: v1
kind: PersistentVolume
metadata:
  name: webook-mysql-pv-v1
spec:
  storageClassName: webook
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"