apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-pv-claim-v1
spec:
  storageClassName: webook
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
