apiVersion: apps/v1
kind: Deployment
metadata:
  name: webook
  labels:
    app: webook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webook
  template:
    metadata:
      name: webook
      labels:
        app: webook
    spec:
      containers:
        - name: webook
          image: yakumo/webook:0.0.1
          ports:
            - containerPort: 8180
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      