// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"webook/internal/ioc"
	"webook/internal/repository"
	"webook/internal/repository/cache"
	"webook/internal/repository/dao"
	"webook/internal/service"
	"webook/internal/web"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	v := ioc.InitMiddleware(cmdable)
	db := ioc.InitGorm()
	userDao := dao.NewUserDao(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDao, userCache)
	userDetailDao := dao.NewUserDetailDao(db)
	userDetailRepository := repository.NewUserDetailRepository(userDetailDao, userCache)
	userService := service.NewUserService(userRepository, userDetailRepository)
	userHandler := web.NewUserHandler(userService)
	engine := ioc.InitGin(v, userHandler)
	return engine
}
